### ISSUE TITLE
Support asynchronous validations like username availability

### ISSUE THREAD

**Issue by ronen-e** [fiverr/passable#10]
Does the package support asynchronous validations? for example, validating username availability.
I didn't see any support, unless I missed it.

**Comment by ealush** [comment]
Hey @ronen-e,
At the moment async validations are not supported as a part of the API due to two reasons:
1. Running async validations may present unexpected complications when running on multiple environments (ie - browser and server).
2. Passable is not intended as a general code runner, but as a structured validations engine, and the code you run within your spec needs to mostly handle data validation enforcements.

You could, as a way to overcome it, make your async requests prior to running your spec and pass the data to your spec. You still gain the benefit of a structured spec, and of a structured response.

**Comment by ronen-e** [comment]
You mean something like this?

```js
.......
data.isAvailable = await isUserAvailable(username)  // return a promise which resolves to true or false
.......
enforce(data.isAvailable).allOf({
    isEmpty: false
});
```

**Comment by ealush** [comment]
Exactly.
It may seem like it would be redundant passing it over to Passable at this stage, since you already have your field validation result (i.e - yes, the user already exists).

I believe there is an added benefit here, as I described before: passing it over to your spec means you get it as a part of your structured response object, and you can still use Passable's API to easily describe cross-dependencies and other validation rules for the same field.

All this is not to say that Passable will never support an Async interface. As more and more browsers support modern APIs, and transpiled code bridges between supported and unsupported environments, it would be a very reasonable step forward for future versions of Passable. 👍

**Comment by ealush** [comment]
@ronen-e, it took a while, but it is being worked on here: https://github.com/fiverr/passable/commit/9730d722a9c2ecc0c8c361badb685cbddc2a0110

Suggested syntax: Use promise as async test. When resolved, the test passes, and when rejected, the test fails. You can have multiple async tests in one suite, and have mixed sync and async tests. Furthermore, no need to wait for all tests to finish to access the current validation state.

```js
import passable, {enforce} from 'passable';

passable('formname', (test) => {
    test('sync', 'sync example', () => {
        enforce(something).isTruthy();
    });

    test('async', 'async example', new Promise((resolve, reject) => {
        fetch(...)
           .then(...)
           .then((data) => if (data.userExists) { reject(); });
    });
});
```

**Comment by ealush** [comment]
Hey @ronen-e,, thanks for the response. I see in your code example that you, too, noticed the problematic part of this approach. We initially tested using the `done` callback, but then we realized that there is no simple way in this syntax to indicate a failing test - thus the timeout.
The timeout is great for the unit testing, but not so much for production applications which provide feedback to the consumer either by a ui change, or an http response. 

In your example, if the test fails within 1 ms(syntax error, for example), it will still wait almost 5 more seconds until the suite fails. This is undesirable.

Adding the async/await is also not something we want, as it makes the block itself sync, which kind of takes the sting out of the whole async test. We want stuff to run in parallel without flexing.

... 
We later tried a similar approach with done and fail callbacks:

```js
test('field', 'some statement', (done, fail) => {...});
```
Calling done will complete the test, fail will mark it as failed and complete it (in this order). The problem there was that in order to call fail, the consumer would have to manually wrap the async test with try catch blocks, as enforce throws an error. This is not an acceptable api in my opinion.

... 

So the decision was to diverge from the way it is done in non production environments so we can be more performant and responsive, yet provide full control of test passage or failure to the consumer. 

I hope this sums it up well.

**Comment by ronen-e** [comment]
@ealush I may missing something in your explanation but could you not solve this by something like this [code sample together with unit tests](https://jsbin.com/jogofaqihe/1/edit?js,output)

Main code from the sample:

```js
const DEFAULT_TIMEOUT = 1500;

function test(callback) {

  if (callback.length) {

    const DONE = (value) => console.log('done', value);
    const FAIL = (err) => console.log('rejected', err) || done();
    
    const promise = new Promise((resolve, reject) => {
      const T = setTimeout(() => reject('test_timeout'), DEFAULT_TIMEOUT);

      const done = (value) => {
        clearTimeout(T);
        resolve(value);
      };
      
      var result = callback(done);
      
      if (result instanceof Promise) {
        result.then(done, reject);
      }
      
    })
    
    promise.then(DONE, FAIL);
    
    return promise;
    
  }
}
```
The promise is still created but behind the scenes. The user will need to call the `done` method which is provided like in standard async unit testing. 

If the user needs to respond to a rejection immediately they will just need to return a promise from their test callback

If an error is thrown from inside an executing promise it will cause it to reject. 
This works well with `enforce` method which throws errors

```js
test( (done) => setTimeout(done, 1000) ).then(...)
test( (done) => Promise.reject('error') ).catch(...)
test( (done) => throw new Error('error') ).catch(...)
```

**Comment by ealush** [comment]
Hey @ronen-e, thanks for the elaborate response.

The main problem we have with the `done` argument is the inherent reliance on a timeout. A timeout is something we try to avoid. The reason is simple: We want to give the consumer a full control over test failure and success. A timeout gives us a hard time doing this because of two main issues:

1. A timeout does not necessarily mean failure of a test.
2. In production apps, a timeout might need to be different for consumers in different countries or internet connection speeds. Could even be different in peak hours of the site. It is problematic to base your validations on that.
---

Now, your examples show how such a thing would look like for the consumer, and it is mostly clean and familiar. It could get needlessly messy when you want to handle rejection in an async test.

Let's take your first example:
```js
test('name', 'message', (done) => setTimeout(done, 1000));
```

What if you needed to reject there?
```js
test('name', 'message', (done) => new Promise((resolve, reject) => setTimeout(reject, 1000)));
```
One more thing is that in this case you still can't use enforce (or throw) for rejection.
```js
test('name', 'message', (done) => new Promise((resolve, reject) => {
    setTimeout(() => enforce(true).isFalsy(), 1000); // won't really do anything. Will fail by timeout
}));
```
---
I believe that from an API standpoint, a promise maintains a pretty good power-to-weight ratio, prevents a lot of boilerplate wrapper code, and still is pretty easy to use and understand.
