### ISSUE TITLE
Functional Enforce

### ISSUE THREAD

**Issue by Attrash-Islam** [fiverr/passable#101]
Hi @ealush,
I looked that the implementation of passable Enforce was using "class" and "this" keywords and tried to re-implement that in fully functional way here https://github.com/Attrash-Islam/passable-functional-enforce with flat rules folder.

I'd like to have your notes regards the way it was implemented? and if you think that we can change the way it implemented in the original "Passable" package here.

Thank you

**Comment by ealush** [comment]
Hey @Attrash-Islam,
Thanks for reaching out :)

Your implementation is very similar to the way it used to work just a few versions ago. https://github.com/fiverr/passable/commit/57c0f1aff418f002fb42dcb3de57ec777641b686#diff-de84b3d7803b2671f19284c5f74d156dL14 .
There have been two big changes since:

1. Move towards a class based solution
2. Instead of using a manual proxy (your `rulesCombiner` function), we moved to a Proxy object.

The reasons for these changes are:
1. Allow creating an Enforce instance with custom validation rules
2. Improve performance by not iterating all rules when they are not actually needed

You can read more deeply about the reasons for this change in [this article](https://medium.com/fiverr-engineering/writing-a-js-proxy-based-assertion-function-5a7359df9f9b), mainly the change from "The “It’s Christmas time” approach" to "The “Lazy” approach".

**Comment by Attrash-Islam** [comment]
Hi!
Thanks for responding.

Regards the moving to class based solution that is related to the team suggestion that is not counted as a advantage since the dynamic unstable "this" binding in JavaScript made it as dangerous road, even Kent Beck -One of OOP scientists- complained about this binding unstable behavior.. but still this is the team decision and I don't reject it being easily maintained by a great developers but still I've the doubts to call it as an advantage to the product specially in the JavaScript context.

Now, regards the proxy I didn't understand how it's more performance better the ruleCompiners. At the end of the bundle your proxy object and mine will include all the functions bounded into it and they'll be called just when you call them, and in the two cases they'll be loaded in the memory.

(Sounds like I didn't got the idea of the proxy)

**Comment by ealush** [comment]
Hey @Attrash-Islam :)

1. 
Creating an enforce instance is used to allow extending enforce with custom validations. This means that we support adding more validations to enforce when needed, for example:

```js
const enforce = new Enforce({
    isValidEmail: isValidEmailFunc
});
```

And later on you can use it like this:

```js
enforce('email@example.com').isVaildEmail()
````

2.
The Proxy Object is more performant for one main reason - it does not iterate all the rules upon initialization, but instead - it only looks it up upon usage. Meaning that only rules that are actually being used will be taken into account. Sort of a lazy assignment.

My tests showed a 5X time reduction when moving from eager to lazy rule assignment:
![image](https://user-images.githubusercontent.com/11255103/47142690-26becd00-d2cc-11e8-8b27-b9df0be0e10f.png)

**Comment by Attrash-Islam** [comment]
Hi 😃 
Sounds very interesting the Proxy metrics you showed! Will likely read more about this

Thanks a lot
