### ISSUE TITLE
Either document or deprecate the undocumented .fin() api

### ISSUE THREAD

**Issue by ealush** [fiverr/passable#19]
`.fin()` is a function that can be chained to an `enforce` function to get a boolean with the result of that enforce. It is currently undocumented in the docs. We should either deprecate it, as it is not really useful, or document and maintain it.

**Comment by ronen-e** [comment]
It should be deprecated. It is only used to make testing easier.
You could achieve the same result in the specs with something like:
```js
import _enforce from './index';

const enforce = function(...args) {
  let response = _enforce(...args);
  response.fin = () => Boolean(response.valid);
  return response;
}

// in your test
const res1 = enforce(5).allOf({ largerThan: 4 }).fin()
```

Though, I would rather remove it completely and change the tests accordingly.

**Comment by ealush** [comment]
The `.fin()` api was not created for tests, it was initially created for cases in which the developer writing the validation could integrate their own logic along with the enforce function, without necessarily throwing.

```
pass('field name', 'field comment', () => {
    const result = enforce(data).allOf(...).anyOf(...).fin(); // returns a boolean
    return result && someOtherFuncion(); // here we return the result instead of throwing on failure
});

**Comment by ronen-e** [comment]
Then you could document it. Though you might want to change the name to something more context related like `result` or `isValid` and make it a getter like so:
```js
...........
get isValid() { return !!this.valid; }

...........

pass('field name', 'field comment', () => {
    const result = enforce(data).allOf(...).anyOf(...).isValid; // returns a boolean
    return result && someOtherFuncion(); // here we return the result instead of throwing on failure
});
```

**Comment by ronen-e** [comment]
On second thought, you should deprecate `fin()`.

`enforce` throws an exception on any non valid result.
Meaning, it is already __implied__ that if an exception is thrown the test failed.

so in your previous example the custom logic would not run on a failed `enforce`, because an exception would be thrown by then.

In order to run custom logic with `enforce` you would have to use `try catch`

```js
pass('field name', 'field comment', () => {
  try {
    const result = enforce(data).allOf(...).anyOf(...).fin(); // returns a boolean
    return result && someOtherFuncion(); // here we return the result instead of throwing on failure    
  } catch (e) {
    return false;
  }
});

```

`pass` treats any exception like a failed test.
So in this context - it is like writing:
```js
pass('field name', 'field comment', () => {
  enforce(data).allOf(...).anyOf(...);
  return someOtherFuncion();  // implicitly assume enforce passed successfully
});
```

Meaning, in this context `fin()` does not serve a useful purpose.
You could __not__ throw an exception from `enforce`, and then `fin()` might be useful.

**Comment by ealush** [comment]
Yes, this is currently what making fin useless, but it does have easy enough solutions.

In an offline conversation with @omrilotan we came up with the thought of adding a `noThrow` option to `enforce`, and so it looks somewhat like this:
```js
enforce(data).noThrow().allOf(...).anyOf().fin()
```

Or a throw boolean argument to enforce that determine whether it throws or not. 
```js
enforce(data, false).allOf(...).anyOf().fin()
```

This way we could use fin as a chain breaking function in the chain to return the value, and use the value later on for other purposes (as shown in my previous comment). You will, of course, have to use `fin()` along with `noThrow`, and but that's pretty much the whole point.

**Comment by ronen-e** [comment]
I'm not sure about the use cases for `fin()` even when disabling exceptions. Especially given the alternatives.

I'm not sure about the logic, regarding how `enforce` works internally.

## Current Logic
```js
function run(group, tests) {
  if (isInvalid(self.valid)) {
    return self;
  }

  self.valid = runners[group](value, tests, allRules);

  if (self.valid !== true) {
    throw new Error(`[Passable] 'Enforce': ${group} - invalid ${typeof value} value`);
  }

  return self;
}
```
### Breakdown
1. set `valid` property of result object to test result
1. if invalid - throw exception
1. return result
1. (on nth pass) - if invalid result and still running (assuming no exception thrown) - return result and do not execute other tests

## `fin()` always returns false on invalid result
Based on current logic an invalid test means no additional tests will be performed. So the value of `fin()` will always be `false` once you have an invalid result. For example:
```js
enforce(data, false).allOf(...)  // If the allOf test result is invalid
.anyOf(...)                      // anyOf is never executed
.noneOf(...)                     // neither is noneOf ever executed
```
## Using `fin()` when exceptions are disabled
So in order to use `fin()` with any meaning when chaining you will need to do something like:
```js
let result = enforce(value).allOf(...).fin();
...
result = result.anyOf(...).fin();
...
result = result.noneOf(...).fin();
...
```
This seems somewhat unnecessary.

## `fin()` Alternatives Guidelines:
### Guideline 1
Use the already present `valid` property on the result object:
```js
let result = enforce(value).allOf(...).valid;
...
```
If you want to set valid to be only `true / false` you could take care of that inside the internal `run` function.

### Guideline 2
Prefer not running custom logic with `enforce` in the same `pass` block. 
You could use a different `pass` block for that. 
This assumes that `enforce` helps the user without having to define his own logic. In cases where  `enforce` is not enough than the user should define specific custom logic.

```js
pass('field name', 'field comment 1', () => {
  enforce(data).allOf(...).anyOf(...);
});

pass('field name', 'field comment 2', () => {
  return someOtherFuncion(); 
});
```
### Guideline 3
Run custom logic while assuming enforce fails by throwing an exception.
Use `try catch` where necessary (as shown [previously](https://github.com/fiverr/passable/issues/19#issuecomment-340344826).

**Comment by ealush** [comment]
I am not completely sure I understand the reasoning behind your chaining example when exceptions are disabled. Even when exceptions disabled, you could still easily chain the functions all the way through the `.fin()`. Yes - the runners will need to be modified so that they do not throw, and also skip all runners after a failed test, and simply return the value on `.fin()`.

It should be done pretty much like this:

| `enforce(data)` | `.noThrow()` | `.allOf(...)` | `.anyOf(...)` | `.fin()`           |
|-----------------|--------------|------------|-------------|---------------|
|              -             |          -            | fail . skip    | skip              | `return false` |

This would be a minor change in how the runners currently work, similar to what I wrote below:
```js
function run(group, tests) {
  if (isInvalid(self.valid)) {
    return self;
  }

  if (self.valid !== false) { // we did not explicitly fail
      self.valid = runners[group](value, tests, allRules);
  }

  if (self.valid !== true && !self.noThrow) { // we only throw if we failed and noThrow was specified
    throw new Error(`[Passable] 'Enforce': ${group} - invalid ${typeof value} value`);
  }

  return self;
}
```

----------

Regarding the guidelines:

### Guideline 1
We still need to handle some kind of `noThrow` functionality to arrive at the `.valid`; either by making the user `try/catch` or by adding the `noThrow` option.

### Guideline 2
**While I generally agree with you** (different checks should be in different `pass` functions), I believe that we should not make it a constraint in the API, as it is simple enough to support, and I can imagine use cases in which consumers would want to mix types.

### Guideline 3
I personally believe we do not need to force consumers to verbosely `try` and `catch` within their `pass` function when we can **very** easily support that in our API. 

----------

I am mostly with you on **Guideline 2** and I think that it should be expended and added as a part of the documentation to the best practices of writing tests.
* Tests should be kept as simple as possible
* Since multiple `pass` functions can be written for the same field, when dealing with multiple separate conditions, they should be separated into multiple `pass` functions for the same field.

Also, your alternative examples that are currently supported in the API should be documented as possible use cases. **Not because that's something we support in our API** (`try/catch` would work regardless of whether we support it or not), but since it would show consumers how they can use the API in more advanced cases.

--------

I'll have to give it some more thought, as `.fin()` is by design a less frequent API, and that's the main reason I am considering to deprecate it - on the other hand, as mentioned earlier, it can help consumers in more complex use-cases.

**Comment by ealush** [comment]
`.fin()` is dead. Will be removed in the next major, as it produces little to none added value to the functions that already exist.

Closing.
